// Generated by CoffeeScript 1.10.0
(function() {
  var config, fs, yaml;

  yaml = require('js-yaml');

  fs = require('fs');

  config = fs.readFileSync('./config.yaml', 'utf8');

  module.exports = yaml.load(config);

}).call(this);
